# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='review',
            field=models.CharField(max_length=600),
        ),
    ]
