# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reviews', '0002_auto_20200726_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_review',
            old_name='review',
            new_name='comment',
        ),
    ]
