# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reviews', '0003_auto_20200726_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review',
            name='comment',
            field=models.TextField(),
        ),
    ]
