# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_reviews', '0004_auto_20200726_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review',
            name='headline',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
