# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='aim',
            field=models.CharField(choices=[('lose weight', 'lose weight'), ('maintenance', 'maintenance'), ('gain muscle', 'gain muscle')], default='', max_length=200),
        ),
    ]
