# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0002_macro_aim'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='daily_calorie_goal',
            field=models.FloatField(default=0),
        ),
    ]
