# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0003_macro_daily_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='aim',
            field=models.CharField(choices=[('lose weight', 'lose weight'), ('maintain', 'maintain'), ('gain muscle', 'gain muscle')], default='', max_length=200),
        ),
    ]
