# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0004_auto_20200802_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='carb_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macro',
            name='fat_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macro',
            name='protein_weight',
            field=models.FloatField(default=0),
        ),
    ]
