# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0005_auto_20200802_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='carb_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macro',
            name='fat_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macro',
            name='protein_percent',
            field=models.FloatField(default=0),
        ),
    ]
