# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0006_auto_20200803_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='activity_level',
            field=models.CharField(choices=[('little exercise', 'little exercise'), ('moderate exercise', 'moderate exercise'), ('heavy exercise', 'heavy exercise')], default='', max_length=200),
        ),
    ]
