# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0007_auto_20200804_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical',
            name='unit_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='physical',
            name='unit_type',
            field=models.CharField(choices=[('Imperial', 'Imperial ( inch, pound )'), ('Metric', 'Metric ( cm, kg )')], default='Metric', max_length=200),
        ),
        migrations.AddField(
            model_name='physical',
            name='unit_weight',
            field=models.FloatField(default=0),
        ),
    ]
