# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0008_auto_20200815_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='unit_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='macro',
            name='unit_type',
            field=models.CharField(choices=[('Imperial', 'Imperial ( Inch/Pound )'), ('Metric', 'Metric ( Cm/Kg )')], default='Metric', max_length=200),
        ),
        migrations.AddField(
            model_name='macro',
            name='unit_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='physical',
            name='unit_type',
            field=models.CharField(choices=[('Imperial', 'Imperial ( Inch/Pound )'), ('Metric', 'Metric ( Cm/Kg )')], default='Metric', max_length=200),
        ),
    ]
