# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='None', max_length=50),
        ),
    ]
