# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman'), ('kids', 'kids')], default='None', max_length=30),
        ),
    ]
