# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Weights', 'Weights'), ('Benches', 'Benches'), ('Sets', 'Sets'), ('Powders', 'Powders'), ('Vitamins', 'Vitamins')], default='Weights', max_length=30),
        ),
    ]
