# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200722_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Weights', 'Weights'), ('Benches', 'Benches'), ('Accessories', 'Accessories'), ('Supplements', 'Supplements'), ('Vitamins', 'Vitamins')], default='Weights', max_length=30),
        ),
    ]
