# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200722_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=254),
        ),
    ]
